version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: areaf5-php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - mysql
    command: >
      sh -c "composer install --no-interaction && php-fpm"

  nginx:
    image: nginx:1.27-alpine
    container_name: areaf5-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mariadb:10.11
    container_name: areaf5-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_areaf5
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "3307:3306"

volumes:
  db_data:
